[workspace]
name = "tyff"
channels = [ "conda-forge"]
platforms = [ "linux-64", "osx-arm64" ]

[tasks]
run_mypy = "python -m mypy -p 'tyff'"
run_tests = {
    cmd = "python -m pytest -n logical tyff/_tests",
    env = {OPENMM_DEFAULT_PLATFORM="CPU"},
}
dev_tests = {
    cmd = "python -m pytest -x --lf tyff/_tests",
    env = {OPENMM_DEFAULT_PLATFORM="CPU"},
}

[pypi-dependencies]
pydantic = "*"
pyyaml = "*"
numpy = "*"
setuptools_scm = "*"
distributed = "*"
openmm = "==8.4.*"
symengine = "*"
rdkit = "==2023.*"
matplotlib = "*"
panel = "*"
sqlmodel = "*"
dask = "*"
dask-jobqueue = "*"
dask-kubernetes = "*"
rdkit-stubs = "*"
parsl = "*"
rich = "*"
tyff = { path = ".", editable = true }

[dependencies]
openmm = "8.4.*" # need to help Pixi, since conda solve constraints PyPI solve
openff-toolkit = "0.18.*"
openff-interchange = "0.5.*"
openff-nagl-base = "*"
openff-nagl-models = "*"
openmmtools = "*"
pydantic-units = "*"
pytorch = "*"
datasets = "*"
bokeh = "3.9.*"
# probably optional-ish below here
jupyter = "*"
nbconvert = "*"
tensorboard = "*"
tensorboardx = "*"
uncertainties = "*"
openff-packmol = "0.1.*"
openff-evaluator-base = "*"
# shims
pyarrow = "20.*"
rdkit = "2023.*"

[environments]
py312amber = [ "py312", "ambertools", "test", "typing" ]
py312openeye = [ "py312", "openeye", "packmol", "test", "typing" ]
dev = [ "py312", "openeye", "test", "typing", "dev" ]
hpc3 = ["py312", "openeye", "cu130", "packmol" ]

[feature.dev.dependencies]
pymol-open-source = "*"

[feature.dev.pypi-dependencies]
pre-commit = "*"
jupyterlab = "*"
ipython = "*"
ipdb = "*"
ruff = "*"

[feature.ambertools.dependencies]
ambertools = "*"

[feature.openeye]
channels = [ "openeye", "conda-forge" ]
dependencies = { openeye-toolkits = "*" }

[feature.packmol.dependencies]
packmol = ">=20"

[feature.cu130.dependencies]
cuda-version = "13.0"

[feature.py312.dependencies]
python = "3.12.*"

[feature.test.pypi-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"
pytest-mock = "*"
pytest-randomly = "*"

[feature.typing.pypi-dependencies]
mypy = "*"
types-PyYAML = "*"
types-requests = "*"
