[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=61",
  "setuptools-scm>=8",
]

[project]
name = "tyff"
description = "Distributed simulation package"
readme = "README.md"
license = "MIT"
license-files = [ "LICENSE", "LICENSE-3RD-PARTY" ]
maintainers = [
  { name = "Lily Wang", email = "info@openforcefield.org" },
]
authors = [
  { name = "Lily Wang", email = "info@openforcefield.org" },
]
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Topic :: Scientific/Engineering",
]
dynamic = [ "version" ]
dependencies = []
optional-dependencies.doc = [
  "openff-sphinx-theme @ git+https://github.com/openforcefield/openff-sphinx-theme.git@main",
  "sphinx>=1.8",
]
optional-dependencies.test = [
  "pytest>=6",
  "pytest-cov>=3",
  "pytest-xdist>=2.5",
]
urls.Documentation = "https://tyff.readthedocs.io"
urls.Homepage = "https://github.com/openforcefield/tyff"
urls.Issues = "https://github.com/openforcefield/tyff/issues"
urls.Repository = "https://github.com/openforcefield/tyff"

[tool.setuptools]
packages.find.include = [ "tyff*" ]
packages.find.exclude = [ "tyff._tests.data*" ]
packages.find.namespaces = false
include-package-data = false
zip-safe = false

[tool.setuptools_scm]
fallback_version = "0.0.0"

[tool.ruff]
line-length = 119
lint.select = [ "E", "F", "I", "NPY", "RUF", "UP", "W" ]
lint.isort.known-third-party = [ "openff.toolkit", "openff.utilities", "openff.units", "openff.interchange" ]

[tool.ruff.lint.per-file-ignores]
"tyff/potentials/nonbonded.py" = [ "E501" ]

[tool.mypy]
exclude = "tyff/_tests"
ignore_missing_imports = true
python_version = "3.12"
disallow_untyped_defs = false
warn_unused_ignores = true
warn_return_any = true
disable_error_code = [
  "arg-type",
  "assignment",
  "attr-defined",
  "call-arg",
  "call-overload",
  "dict-item",
  "empty-body",
  "index",
  "misc",
  "no-any-return",
  "no-redef",
  "operator",
  "return",
  "return-value",
  "type-arg",
  "union-attr",
  "unused-ignore",
  "valid-type",
  "var-annotated",
]
warn_unused_configs = true

[tool.pytest]
ini_options.minversion = "6.0"
ini_options.testpaths = [ "tyff/_tests" ]
ini_options.addopts = "-v --durations=10 --cov=tyff --cov-report=xml --cov-append --cov-report=term-missing --color=yes"

[tool.coverage]
run.source = [ "tyff" ]
run.omit = [
  "*/__init__.py",
  "*/_tests/*",
]
report.exclude_lines = [
  "if TYPE_CHECKING:",
  "pragma: no cover",
  "raise NotImplementedError",
]
